name: flutter_complete_guide
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
 
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  provider: ^5.0.0
  
  firebase_storage: ^8.0.0
  cloud_firestore: ^2.2.2
  youtube_player_iframe: ^2.1.0
  
  file_picker: ^3.0.3
  flutter_native_splash: ^1.2.0
  
  http: ^0.13.0
  
  google_fonts: ^2.1.0
  video_player: ^2.1.3
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  video_thumbnail: ^0.3.3
  gallery_saver: ^2.1.2
  onesignal_flutter: ^3.1.0
  camera: ^0.8.1+5
  path: ^1.8.0
  # wechat_camera_picker: ^2.2.0
  device_info: ^2.0.2
  
  # photo_manager: ^1.2.5
 
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  image_path: "assets/embrom.png" 
  android: true
  ios: true 
flutter_native_splash: 
  color: "#232323"
  image: assets/embrom.png
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
module:
   
    androidX: true
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/embrom.png

  